//
// SPDX-FileCopyrightText: The LineageOS Project
// SPDX-License-Identifier: Apache-2.0
//

package pil_squasher

import (
	"regexp"

	"github.com/google/blueprint/proptools"

	"android/soong/android"
)

var (
	pctx           = android.NewPackageContext("android/soong/pil_squasher")
	chunkExtRegexp = regexp.MustCompile(`^\.b[0-9]{2}$`)
)

func init() {
	android.RegisterModuleType("pil_squasher", pilSquasherFactory)
	android.RegisterModuleType("pil_squasher_defaults", pilSquasherDefaultsFactory)

	pctx.Import("android/soong/android")
}

type pilSquasherProperties struct {
	// The MDT header file
	Mdt *string `android:"path"`

	// The chunks (.b00, .b01, etc.).
	Srcs []string `android:"path"`

	// Output file name. Defaults to {name}.mbn
	Stem *string

	// Install to a subdirectory of the install path
	Relative_install_path *string

	// The name of the image this module is built for
	ImageVariation string `blueprint:"mutated"`

	// Suffix for the name of Android.mk entries generated by this module
	SubName string `blueprint:"mutated"`
}

type pilSquasher struct {
	android.ModuleBase
	android.DefaultableModuleBase
	properties pilSquasherProperties

	outputFile  android.WritablePath
	installPath android.InstallPath
}

type pilSquasherDefaults struct {
	android.ModuleBase
	android.DefaultsModuleBase
	properties pilSquasherProperties
}

func pilSquasherFactory() android.Module {
	module := &pilSquasher{}
	module.AddProperties(&module.properties)
	android.InitAndroidArchModule(module, android.DeviceSupported, android.MultilibCommon)
	android.InitDefaultableModule(module)
	return module
}

func pilSquasherDefaultsFactory() android.Module {
	module := &pilSquasherDefaults{}
	module.AddProperties(&module.properties)
	android.InitDefaultsModule(module)
	return module
}

var _ android.ImageInterface = (*pilSquasher)(nil)

func (p *pilSquasher) ImageMutatorBegin(ctx android.ImageInterfaceContext) {}

func (p *pilSquasher) ImageMutatorSupported() bool {
	return true
}

func (p *pilSquasher) CoreVariantNeeded(ctx android.ImageInterfaceContext) bool {
	return false
}

func (p *pilSquasher) VendorVariantNeeded(ctx android.ImageInterfaceContext) bool {
	return true
}

func (p *pilSquasher) ProductVariantNeeded(ctx android.ImageInterfaceContext) bool {
	return false
}

func (p *pilSquasher) RamdiskVariantNeeded(ctx android.ImageInterfaceContext) bool {
	return false
}

func (p *pilSquasher) DebugRamdiskVariantNeeded(ctx android.ImageInterfaceContext) bool {
	return false
}

func (p *pilSquasher) RecoveryVariantNeeded(ctx android.ImageInterfaceContext) bool {
	return false
}

func (p *pilSquasher) VendorRamdiskVariantNeeded(ctx android.ImageInterfaceContext) bool {
	return true
}

func (p *pilSquasher) ExtraImageVariations(ctx android.ImageInterfaceContext) []string {
	return nil
}

func (p *pilSquasher) SetImageVariation(ctx android.ImageInterfaceContext, variation string) {
	p.properties.ImageVariation = variation
}

func (p *pilSquasher) InstallInVendor() bool {
	return p.ModuleBase.InstallInVendor() ||
		p.properties.ImageVariation == android.VendorVariation
}

func (p *pilSquasher) InstallInVendorRamdisk() bool {
	return p.ModuleBase.InstallInVendorRamdisk() ||
		p.properties.ImageVariation == android.VendorRamdiskVariation
}

func (p *pilSquasher) getSubname() string {
	if p.properties.ImageVariation == android.VendorRamdiskVariation {
		return "." + android.VendorRamdiskVariation
	}
	return ""
}

func (p *pilSquasher) GenerateAndroidBuildActions(ctx android.ModuleContext) {
	if p.properties.Mdt == nil {
		ctx.PropertyErrorf("mdt", "must specify an MDT header file")
		return
	}
	mdtPath := android.PathForModuleSrc(ctx, proptools.String(p.properties.Mdt))
	if mdtPath.Ext() != ".mdt" {
		ctx.PropertyErrorf("mdt", "expected a .mdt file, got %q", mdtPath.Base())
		return
	}

	if len(p.properties.Srcs) == 0 {
		ctx.PropertyErrorf("srcs", "must specify at least one chunk file (.b00, .b01, etc.)")
		return
	}

	srcPaths := android.PathsForModuleSrc(ctx, p.properties.Srcs)
	for _, src := range srcPaths {
		if !chunkExtRegexp.MatchString(src.Ext()) {
			ctx.PropertyErrorf("srcs", "expected chunk files (.b00, .b01, etc.), got %q", src.Base())
			return
		}
	}

	stem := proptools.StringDefault(p.properties.Stem, ctx.ModuleName()+".mbn")
	p.outputFile = android.PathForModuleOut(ctx, stem)

	rule := android.NewRuleBuilder(pctx, ctx)
	cmd := rule.Command().BuiltTool("pil-squasher")
	cmd.Output(p.outputFile)
	cmd.Input(mdtPath)
	cmd.Implicits(srcPaths)
	rule.Build("pil_squasher", "Squashing firmware")

	p.installPath = android.PathForModuleInstall(ctx, "firmware")
	if subdir := proptools.String(p.properties.Relative_install_path); subdir != "" {
		p.installPath = p.installPath.Join(ctx, subdir)
	}

	ctx.InstallFile(p.installPath, p.outputFile.Base(), p.outputFile)
	ctx.SetOutputFiles(android.Paths{p.outputFile}, "")

	p.properties.SubName = p.getSubname()
}

func (p *pilSquasher) AndroidMkEntries() []android.AndroidMkEntries {
	if p.outputFile == nil {
		return nil
	}

	return []android.AndroidMkEntries{{
		Class:      "ETC",
		SubName:    p.properties.SubName,
		OutputFile: android.OptionalPathForPath(p.outputFile),
		ExtraEntries: []android.AndroidMkExtraEntriesFunc{
			func(ctx android.AndroidMkExtraEntriesContext, entries *android.AndroidMkEntries) {
				entries.SetPath("LOCAL_MODULE_PATH", p.installPath)
				entries.SetString("LOCAL_INSTALLED_MODULE_STEM", p.outputFile.Base())
			},
		},
	},
	}
}
